### ISSUE TITLE
callTVL1.sh : make it invariant to illumination changes

### ISSUE THREAD

**Issue by dyoussef** [mnhrdt/tvl1flow#3]
`gblur 2 $a | plambda  - " x 4 * x(-1,0) -1 * + x(1,0) -1 * + x(0,-1) -1 * + x(0,1) -1 * + " -o $a` is replaced with `blur g 2 $a | plambda - "x,l" -o $a` in callTVL1.sh but it does not seem to work (all zeros image).

**Comment by mnhrdt** [comment]
It seems to work for me.  Can you send me a pair of input images?

**Comment by dyoussef** [comment]
I have an allzeros image with I0.png.

**Comment by mnhrdt** [comment]
I understand, are you using the version of plambda from s2p?  it is outdated and it does not work with the ",l" syntax.  I'll request an update

**Comment by dyoussef** [comment]
I just found... but too late : You were faster than me :)

**Comment by mnhrdt** [comment]
closed as not an issue with this repo
